[project]
name = "my-dagster-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagit>=1.8.6",
    "dagster>=1.8.6",
    "pandas>=2.2.2",
    "requests>=2.32.3",
]
